version: '3.8'

services:
  app:
    image: omaressid/donation:latest
    container_name: donation
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/donation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: omar
    depends_on:
      - db
    networks:
      - donation_network

  db:
    image: mysql:latest  # Use the latest version of MySQL
    container_name: donation_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donation_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - donation_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
    depends_on:
      - sonar_db
    networks:
      - donation_network

  sonar_db:
    image: postgres:latest
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5432:5432"
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - donation_network

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - donation_network

networks:
  donation_network:
    driver: bridge

volumes:
  db_data:
  sonar_db_data:
