version: '3.8'

services:
  app:
    image: omaressidd/donation:latest
    container_name: donation_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/donation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: omar
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: donation_db
    environment:
      MYSQL_ROOT_PASSWORD: omar
      MYSQL_DATABASE: donation_db
    ports:
      - "3306:3306"
