version: '3.8'

services:
  donation:
    container_name: donation
    build: ./OmarEssidd/donation
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/donationApp?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    image: omaressidd/donation:latest
    depends_on:
      - dbmysql

  dbmysql:
    image: "mysql:5.6"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  angular-app:
    image: omaressidd/donationangular:latest
    ports:
      - "4200:80"
    restart: always

volumes:
  db: