version: '3.8'

services:
  app:
    image: omaressidd/donation:latest
    container_name: donation_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/donation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: omar
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: donation_db
    environment:
      MYSQL_ROOT_PASSWORD: omar
      MYSQL_DATABASE: donation_db
    ports:
      - "3306:3306"

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
    depends_on:
      - sonar_db

  sonar_db:
    image: postgres:latest
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5432:5432"

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
