version: '3.8'

services:
  donation:
   
    container_name: donation
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://dbmysql:3306/donation_db?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME= root
      - SPRING_DATASOURCE_PASSWORD= root
    restart: unless-stopped
    image: omaressid/donation:latest

    depends_on:

  dbmysql:
    image: mysql:latest
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  angular-app:
    image: omaressid/donation:latest  # Spécifiez le nom de votre image et la version (dans cet exemple, "latest")
    ports:
      - "4200:80"  # Assurez-vous que les ports correspondent à ceux que vous utilisez dans votre application
    restart: always  # Optionnel : redémarrer toujours le conteneur en cas d'échec

volumes:
  db:
