global:
  scrape_interval: 15s  # Fréquence de collecte des métriques

scrape_configs:
  - job_name: 'donation'  # Nom du job pour votre service donation
    static_configs:
      - targets: ['donation:8085']  # Remplacez par le port exposé de votre service donation
  - job_name: 'grafana'  # Nom du job pour Grafana
    static_configs:
      - targets: ['grafana:3000']  # Ciblez Grafana
